//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace MVCGridDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeMaster
    {
        [Display(Name = "Scheme ID")]
        public int SchemeID { get; set; }

        [Display(Name = "Scheme Name")]
        public string SchemeName { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
